#!/bin/bash
# SPDX-FileCopyrightText: 2023 Alexandra Stone <alexankitty@gmail.com>
# SPDX-FileCopyrightText: 2025-2026 Vitaliy Elin <daydve@smbit.pro>
# SPDX-License-Identifier: GPL-2.0-or-later
# Version: 8 (Modular)

DIR=$(dirname $(readlink -f "$0"))

plasmoidName=$("$DIR/get_metadata.sh" "Id")
projectName="plasma_applet_${plasmoidName}"

if [ -z "$plasmoidName" ]; then
	echo "[build] Error: Couldn't read 'Id' from metadata.json."
	exit 1
fi

if [ -z "$(which msgfmt)" ]; then
	echo "[build] Error: msgfmt command not found. Need to install gettext"
	echo "[build] Running 'sudo apt install gettext'"
	sudo apt install gettext
fi

echo "[build] Compiling messages for $projectName"

rm -rf "$DIR/../contents/locale"

catalogs=$(find . -name '*.po' | sort)
for cat in $catalogs; do
	echo "$cat"
	catLocale=$(basename "${cat%.*}")
	msgfmt -o "${catLocale}.mo" "$cat"

	installPath="$DIR/../contents/locale/${catLocale}/LC_MESSAGES/${projectName}.mo"

	echo "[build] Install to ${installPath}"
	mkdir -p "$(dirname "$installPath")"
	mv "${catLocale}.mo" "${installPath}"
done

echo "[build] Done building messages"
